filter:
    excluded_paths:
        - 'tests/*'
        - 'languages/*'
        - 'includes/loApiClient.php'
checks:
    php:
        fix_php_opening_tag: true
        remove_php_closing_tag: true
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
        remove_extra_empty_lines: true
        avoid_todo_comments: true
        avoid_fixme_comments: true
    javascript:
        no_else_return: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            general:
                linefeed_character: return-newline
            around_operators:
                concatenation: true
            other:
                after_type_cast: false

tools:
  sensiolabs_security_checker: true