build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
filter:
    dependency_paths:
        - wordpress/
        - includes/loApiClient.php
        - includes/loApiClasses.php
        - includes/eduadmin-api-client/
        - libraries/
    excluded_paths:
        - 'tests/*'
        - scripts/